language: go
sudo: false
go:
  - 1.10.2
addons:
  apt:
    packages:
      rpm
install:
  - gem install fpm
  - npm install -g snyk
script:
  - make travis
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - snyk test
